name: Prisma Generate and DB Push

on:
  push:
    branches:
      - main  # 替换成你希望触发的分支

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Prisma
      run: npm install -g prisma@latest
    
    - name: Clone repository
      run: git clone https://github.com/ssangyongsportsorg/Ssport-website.git
    
    - name: Navigate to project directory
      run: cd Ssport-website
    
    - name: Install project dependencies
      run: npm install
    
    - name: Generate Prisma client
      run: npx prisma generate
      
    - name: Apply Prisma migrations
      run: npx prisma db push