name: Prisma Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  prisma:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone Repository
      run: |
        git clone https://github.com/ssangyongsportsorg/Ssport-website.git

    - name: Install Dependencies
      run: npm ci

    - name: Prisma Generate
      run:  npx prisma generate
      

    - name: Prisma DB Push
      run:  npx prisma db push
      
